### ISSUE TITLE
Add a hook for the systemtest and unittest setup files

### ISSUE THREAD

**Issue by tujlaky** [garlictech/workflows#14]
Currently we couldn't create a custom test setup outside of the docker image.

See this file:
https://github.com/garlictech/workflows/blob/2/workflows-common/gulp_common/systemtest.coffee#L12

I created this systemtest.coffee for a project.
I think we need something similar in functionality with a hook:

```
  return ->
    p.env.set NODE_ENV: "test"
    gulp.src ["#{config.buildRoot}/test/system/test.js", "#{config.buildRoot}/test/system/**/*.spec.js"]
    .pipe p.jasmine
      reporter: new SpecReporter
        spec:
          displayPending: true
          displayStacktrace: true
      includeStackTrace: true
```

**Comment by molnarzs** [comment]
In workflow 2.4.0
