### ISSUE TITLE
gulp unittest uses wrong path for globals.js

### ISSUE THREAD

**Issue by tujlaky** [garlictech/workflows#9]
In this line https://github.com/garlictech/workflows/blob/master/workflows-server/gulp/unittest.coffee#L10 globals.js is not loaded because it is not in the buildRoot directory. It is in the buildRoot/base directory.

This is the change which breaks the task:

https://github.com/garlictech/workflows/commit/a3a6488689e99d5b77430882a58c244da087d2d5#diff-f677297d16e45875b2c4579dae8f9aa2R23

**Comment by tujlaky** [comment]
See this build for example: https://travis-ci.com/garlictech/authentication-server/builds/35262896

**Comment by molnarzs** [comment]
Fixed.
